Indexing & slicing

In [ ]:
import numpy as np 
data=np.array([10,20,30,40,50,60])
print(data)
print(data[3])
print(data[2:4])
print(data[-2])
print(data[-4:-2])
print(data[::-1])

In [ ]:
arr=np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])
print(arr)
print(arr[1,1])
print(arr[2,2])
print(arr[:,0])
print(arr[:2,:])
print(arr[1:,1:])

In [ ]:
import numpy as np
import pandas as pd
np.random.seed(42)
rows = 1000
df = pd.DataFrame({
"Student_ID": range(1, rows + 1),
"Age": np.random.randint(18, 26, rows),
"Study_Hours": np.random.randint(1, 11, rows),
"Attendance": np.random.randint(60, 101, rows),
"Assignments": np.random.randint(1, 11, rows),
"Previous_Marks": np.random.randint(40, 101, rows),
"Sleep_Hours": np.random.randint(4, 10, rows),
"Internet_Usage": np.random.randint(1, 9, rows),
"Marks": np.random.randint(35, 101, rows)
})
print(df.head())
df.to_csv("student_performance_1000.csv", index=False)

In [ ]:
print(df.head())
print(df.tail())
print(df.shape)
print(df.columns)
print(df.info())
print(df.describe())

In [ ]:
import numpy as np
import pandas as pd
np.random.seed(42)
rows = 1000
df = pd.DataFrame({
"Student_ID": range(1, rows + 1),
"Age": np.random.randint(18, 26, rows),
"Study_Hours": np.random.randint(1, 11, rows),
"Attendance": np.random.randint(60, 101, rows),
"Assignments": np.random.randint(1, 11, rows),
"Previous_Marks": np.random.randint(40, 101, rows),
"Sleep_Hours": np.random.randint(4, 10, rows),
"Internet_Usage": np.random.randint(1, 9, rows),
"Marks": np.random.randint(35, 101, rows)
})
df.to_csv("student_performance_1000.csv", index=False)
arr=df.to_numpy()
print(arr)

In [ ]:
print(arr[4])

In [ ]:
print(arr[-1])

In [ ]:
print(arr[0])
print(arr[0][8])
print(arr[9,3])

In [ ]:
print(arr[10::])

In [ ]:
print(arr[:,2])

In [ ]:
print(np.mean(arr[:,2]))
print(np.median(arr[:,2]))
from scipy import stats
print(stats.mode(arr[:,2]))

Probability
Vectors
Class And Object 
Correlation
Feature intution
condtions
loops
matrix

In [ ]:
import numpy as np
import pandas as pd
np.random.seed(42)
rows = 1000
df = pd.DataFrame({
"Student_ID": range(1, rows + 1),
"Age": np.random.randint(18, 26, rows),
"Study_Hours": np.random.randint(1, 11, rows),
"Attendance": np.random.randint(60, 101, rows),
"Assignments": np.random.randint(1, 11, rows),
"Previous_Marks": np.random.randint(40, 101, rows),
"Sleep_Hours": np.random.randint(4, 10, rows),
"Internet_Usage": np.random.randint(1, 9, rows),
"Marks": np.random.randint(35, 101, rows)
})
df.to_csv("student_performance_1000.csv", index=False)
arr=df.to_numpy()
#print(arr)
 
#1 Probability 
prob = np.sum(df["Marks"] > 80) / len(df)
print("Probability:", prob)

#2 Vector 
study = df["Study_Hours"].to_numpy()
marks = df["Marks"].to_numpy()

print("Study Hours Vector:")
print(study)

print("Vector Addition:")
print(study + marks)

print("Dot Product:")
print(np.dot(study, marks))
#3 class Object
class Student:
    def __init__(self, age, marks):
        self.age = age
        self.marks = marks

    def display(self):
        print("Age:", self.age)
        print("Marks:", self.marks)

s1 = Student(df["Age"][0], df["Marks"][0])
s1.display()
#4 correlation
corr = df.corr()

print(corr)

print("Study Hours vs Marks")
print(df["Study_Hours"].corr(df["Marks"]))
#5 
print(df.describe())

print("Average Marks:", df["Marks"].mean())
print("Average Study Hours:", df["Study_Hours"].mean())
#6
high = df[df["Marks"] >= 75]

print(high.head())
#7
for row in arr[:5]:
    print(row)
#8
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

print("Addition")
print(A+B)

print("Subtraction")
print(A-B)

print("Multiplication")
print(A@B)

vectorization

In [ ]:
import numpy as np
import pandas as pd
df=pd.read_csv("student_performance_1000.csv")
print(df.head())

In [ ]:
marks=df['Marks'].to_numpy()
attendence=df['Attendance'].to_numpy()
studyHours=df['Study_Hours'].to_numpy()
previous=df['Previous_Marks'].to_numpy()
print(type(marks))

In [ ]:
marks_list=marks.tolist()
marks_list=marks + 5
print(marks_list[:10])
print(marks[:10])

In [ ]:
studyHours=np.multiply(studyHours,marks)
print(studyHours[:10])
print(marks[:10])

universal function

In [ ]:
print(np.sqrt(marks[:10]))
print(np.log(marks[:10]))
print(np.exp(studyHours[:10]))
print(np.sin(studyHours[:10]))

In [2]:
! pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\sujan sure\onedrive\desktop\aiml-3\virtual\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\sujan sure\onedrive\desktop\aiml-3\virtual\lib\site-packages (from openpyxl) (2.0.0)

[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd
df=pd.read_excel("data.xlsx")
print(df.head())

  Unnamed: 0      ID   Salary        DOJ                  DOL  \
0      train  203097   420000 2012-06-01              present
1      train  579905   500000 2013-09-01              present
2      train  810601   325000 2014-06-01              present
3      train  267447  1100000 2011-07-01              present
4      train  343523   200000 2014-03-01  2015-03-01 00:00:00

                Designation    JobCity Gender        DOB  10percentage  ...  \
0   senior quality engineer  Bangalore      f 1990-02-19          84.3  ...
1         assistant manager     Indore      m 1989-10-04          85.4  ...
2          systems engineer    Chennai      f 1992-08-03          85.0  ...
3  senior software engineer    Gurgaon      m 1989-12-05          85.6  ...
4                       get    Manesar      m 1991-02-27          78.0  ...

  ComputerScience  MechanicalEngg  ElectricalEngg TelecomEngg  CivilEngg  \
0              -1              -1              -1          -1         -1
1              -1              -1              -1          -1         -1
2              -1              -1              -1          -1         -1
3              -1              -1              -1          -1         -1
4              -1              -1              -1          -1         -1

   conscientiousness agreeableness extraversion  nueroticism  \
0             0.9737        0.8128       0.5269      1.35490
1            -0.7335        0.3789       1.2396     -0.10760
2             0.2718        1.7109       0.1637     -0.86820
3             0.0464        0.3448      -0.3440     -0.40780
4            -0.8810       -0.2793      -1.0697      0.09163

   openess_to_experience
0                -0.4455
1                 0.8637
2                 0.6721
3                -0.9194
4                -0.1295

[5 rows x 39 columns]

In [1]:
%pip install openpyxl

Collecting openpyxl
  Using cached openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Using cached et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Using cached openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Using cached et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("HTTPSConnection(host='pypi.org', port=443): Failed to resolve 'pypi.org' ([Errno 11001] getaddrinfo failed)")': /simple/openpyxl/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("HTTPSConnection(host='pypi.org', port=443): Failed to resolve 'pypi.org' ([Errno 11001] getaddrinfo failed)")': /simple/openpyxl/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("HTTPSConnection(host='pypi.org', port=443): Failed to resolve 'pypi.org' ([Errno 11001] getaddrinfo failed)")': /simple/openpyxl/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("HTTPSConnection(host='pypi.org', port=443): Failed to resolve 'pypi.org' ([Errno 11001] getaddrinfo failed)")': /simple/openpyxl/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("HTTPSConnection(host='pypi.org', port=443): Failed to resolve 'pypi.org' ([Errno 11001] getaddrinfo failed)")': /simple/openpyxl/

In [3]:
import pandas as pd
df=pd.read_excel("data.xlsx")
df.duplicated().sum()

np.int64(0)

In [4]:
for i in df.columns:
    print(df[i].unique())

<ArrowStringArray>
['train']
Length: 1, dtype: str
[203097 579905 810601 ... 355888 947111 324966]
[ 420000  500000  325000 1100000  200000  300000  400000  600000  230000
  450000  270000  350000  250000  120000  320000  190000  180000  335000
  435000  345000  145000  220000  530000  340000  360000  215000   80000
  330000  380000  110000  205000   95000  390000   60000  240000  525000
  305000  150000  310000  455000  800000  100000  280000  445000  315000
  370000  275000 1500000  425000  470000  460000  510000  480000  170000
  640000  225000  440000 1200000  675000  105000  195000  385000  235000
  615000  290000  140000  405000 1860000  375000  430000  660000   70000
  410000  550000   35000  115000  415000  265000  285000  245000  395000
  560000  700000  185000  160000  625000   85000  135000  785000  210000
  155000  355000  535000  690000  260000 1110000 1000000  505000  475000
  715000  820000   90000  720000 2600000  515000   55000  495000   65000
  655000  545000  520000  645000 1025000  775000  490000 1300000 3500000
  910000  570000  255000  130000  175000  730000  555000  465000  680000
  165000  630000  365000 1050000 2000000  860000  125000   50000  580000
  485000 4000000 2020000  650000   45000  610000  760000  585000  620000
  870000 2050000  540000  144000  605000 1320000  755000  880000 3000000
   75000  295000   40000  575000  565000 2500000 2300000  590000  950000
 1800000  725000  930000  750000  705000 1745000  850000  845000  670000
 1030000  770000  900000 1210000  810000  925000]
<DatetimeArray>
['2012-06-01 00:00:00', '2013-09-01 00:00:00', '2014-06-01 00:00:00',
 '2011-07-01 00:00:00', '2014-03-01 00:00:00', '2014-08-01 00:00:00',
 '2014-07-01 00:00:00', '2013-07-01 00:00:00', '2011-04-01 00:00:00',
 '2011-08-01 00:00:00', '2013-12-01 00:00:00', '2014-01-01 00:00:00',
 '2013-08-01 00:00:00', '2014-09-01 00:00:00', '2010-11-01 00:00:00',
 '2012-08-01 00:00:00', '2013-10-01 00:00:00', '2012-09-01 00:00:00',
 '2011-01-01 00:00:00', '2015-02-01 00:00:00', '2014-11-01 00:00:00',
 '2011-12-01 00:00:00', '2014-10-01 00:00:00', '2015-01-01 00:00:00',
 '2013-03-01 00:00:00', '2010-10-01 00:00:00', '2013-01-01 00:00:00',
 '2011-06-01 00:00:00', '2014-04-01 00:00:00', '2012-05-01 00:00:00',
 '2012-10-01 00:00:00', '2015-04-01 00:00:00', '2012-03-01 00:00:00',
 '2013-06-01 00:00:00', '2009-09-01 00:00:00', '2013-11-01 00:00:00',
 '2010-07-01 00:00:00', '2014-02-01 00:00:00', '2015-06-01 00:00:00',
 '2014-05-01 00:00:00', '2014-12-01 00:00:00', '2011-11-01 00:00:00',
 '2015-07-01 00:00:00', '2013-05-01 00:00:00', '2011-03-01 00:00:00',
 '2015-03-01 00:00:00', '2012-07-01 00:00:00', '2011-10-01 00:00:00',
 '2010-04-01 00:00:00', '2013-04-01 00:00:00', '2010-12-01 00:00:00',
 '2013-02-01 00:00:00', '2011-09-01 00:00:00', '2012-02-01 00:00:00',
 '2012-01-01 00:00:00', '2012-12-01 00:00:00', '2010-09-01 00:00:00',
 '2012-04-01 00:00:00', '2012-11-01 00:00:00', '2015-05-01 00:00:00',
 '2010-06-01 00:00:00', '2011-02-01 00:00:00', '2010-08-01 00:00:00',
 '2010-05-01 00:00:00', '2011-05-01 00:00:00', '2004-08-01 00:00:00',
 '2008-11-01 00:00:00', '2009-06-01 00:00:00', '2010-02-01 00:00:00',
 '2009-11-01 00:00:00', '2010-03-01 00:00:00', '2015-11-01 00:00:00',
 '2006-01-01 00:00:00', '2015-08-01 00:00:00', '2010-01-01 00:00:00',
 '2015-12-01 00:00:00', '2007-09-01 00:00:00', '1991-06-01 00:00:00',
 '2007-07-01 00:00:00', '2007-06-01 00:00:00', '2007-02-01 00:00:00']
Length: 81, dtype: datetime64[us]
['present' datetime.datetime(2015, 3, 1, 0, 0)
 datetime.datetime(2015, 5, 1, 0, 0) datetime.datetime(2015, 7, 1, 0, 0)
 datetime.datetime(2015, 4, 1, 0, 0) datetime.datetime(2014, 10, 1, 0, 0)
 datetime.datetime(2014, 9, 1, 0, 0) datetime.datetime(2014, 6, 1, 0, 0)
 datetime.datetime(2012, 9, 1, 0, 0) datetime.datetime(2013, 12, 1, 0, 0)
 datetime.datetime(2015, 6, 1, 0, 0) datetime.datetime(2013, 10, 1, 0, 0)
 datetime.datetime(2015, 1, 1, 0, 0) datetime.datetime(2014, 4, 1, 0, 0)
 datetime.datetime(2013, 6, 1, 0, 0) datetime.datetime(2012, 3, 1, 0, 0)
 datetime.datetime(2014, 7, 1, 0, 0) datetime.datetime(2013, 2, 1, 0, 0)
 datetime.datetime(2014, 1, 1, 0, 0) datetime.datetime(2013, 4, 1, 0, 0)
 datetime.datetime(2012, 7, 1, 0, 0) datetime.datetime(2014, 5, 1, 0, 0)
 datetime.datetime(2013, 9, 1, 0, 0) datetime.datetime(2015, 2, 1, 0, 0)
 datetime.datetime(2012, 1, 1, 0, 0) datetime.datetime(2015, 8, 1, 0, 0)
 datetime.datetime(2014, 8, 1, 0, 0) datetime.datetime(2015, 12, 1, 0, 0)
 datetime.datetime(2014, 12, 1, 0, 0) datetime.datetime(2012, 5, 1, 0, 0)
 datetime.datetime(2011, 3, 1, 0, 0) datetime.datetime(2011, 7, 1, 0, 0)
 datetime.datetime(2014, 2, 1, 0, 0) datetime.datetime(2011, 12, 1, 0, 0)
 datetime.datetime(2015, 10, 1, 0, 0) datetime.datetime(2014, 11, 1, 0, 0)
 datetime.datetime(2014, 3, 1, 0, 0) datetime.datetime(2011, 11, 1, 0, 0)
 datetime.datetime(2013, 5, 1, 0, 0) datetime.datetime(2013, 7, 1, 0, 0)
 datetime.datetime(2013, 11, 1, 0, 0) datetime.datetime(2011, 1, 1, 0, 0)
 datetime.datetime(2011, 5, 1, 0, 0) datetime.datetime(2012, 2, 1, 0, 0)
 datetime.datetime(2012, 11, 1, 0, 0) datetime.datetime(2012, 6, 1, 0, 0)
 datetime.datetime(2013, 8, 1, 0, 0) datetime.datetime(2005, 3, 1, 0, 0)
 datetime.datetime(2013, 3, 1, 0, 0) datetime.datetime(2012, 10, 1, 0, 0)
 datetime.datetime(2011, 2, 1, 0, 0) datetime.datetime(2010, 2, 1, 0, 0)
 datetime.datetime(2013, 1, 1, 0, 0) datetime.datetime(2011, 6, 1, 0, 0)
 datetime.datetime(2015, 9, 1, 0, 0) datetime.datetime(2012, 4, 1, 0, 0)
 datetime.datetime(2012, 8, 1, 0, 0) datetime.datetime(2011, 4, 1, 0, 0)
 datetime.datetime(2011, 10, 1, 0, 0) datetime.datetime(2015, 11, 1, 0, 0)
 datetime.datetime(2012, 12, 1, 0, 0) datetime.datetime(2011, 9, 1, 0, 0)
 datetime.datetime(2010, 8, 1, 0, 0) datetime.datetime(2011, 8, 1, 0, 0)
 datetime.datetime(2009, 6, 1, 0, 0) datetime.datetime(2008, 3, 1, 0, 0)
 datetime.datetime(2010, 10, 1, 0, 0)]
<ArrowStringArray>
[       'senior quality engineer',              'assistant manager',
               'systems engineer',       'senior software engineer',
                            'get',                'system engineer',
         'java software engineer',            'mechanical engineer',
            'electrical engineer',               'project engineer',
 ...
          'recruitment associate',            'logistics executive',
             'quality consultant',         'senior sales executive',
                        'db2 dba',                'test technician',
        'it operations associate', 'software engineering associate',
             'research scientist',         'jr. software developer']
Length: 419, dtype: str
['Bangalore' 'Indore' 'Chennai' 'Gurgaon' 'Manesar' 'Hyderabad' 'Banglore'
 'Noida' 'Kolkata' 'Pune' -1 'mohali' 'Jhansi' 'Delhi' 'Hyderabad '
 'Bangalore ' 'noida' 'delhi' 'Bhubaneswar' 'Navi Mumbai' 'Mumbai'
 'New Delhi' 'Mangalore' 'Rewari' 'Gaziabaad' 'Bhiwadi' 'Mysore' 'Rajkot'
 'Greater Noida' 'Jaipur' 'noida ' 'HYDERABAD' 'mysore' 'THANE'
 'Maharajganj' 'Thiruvananthapuram' 'Punchkula' 'Bhubaneshwar' 'Pune '
 'coimbatore' 'Dhanbad' 'Lucknow' 'Trivandrum' 'kolkata' 'mumbai'
 'Gandhi Nagar' 'Una' 'Daman and Diu' 'chennai' 'GURGOAN' 'vsakhapttnam'
 'pune' 'Nagpur' 'Bhagalpur' 'new delhi - jaisalmer' 'Coimbatore'
 'Ahmedabad' 'Kochi/Cochin' 'Bankura' 'Bengaluru' 'Mysore ' 'Kanpur '
 'jaipur' 'Gurgaon ' 'bangalore' 'CHENNAI' 'Vijayawada' 'Kochi' 'Beawar'
 'Alwar' 'NOIDA' 'Greater noida' 'Siliguri ' 'raipur' 'gurgaon' 'Bhopal'
 'Faridabad' 'Jodhpur' 'udaipur' 'Muzaffarpur' 'Kolkata`' 'Bulandshahar'
 'Haridwar' 'Raigarh' 'Visakhapatnam' 'Jabalpur' 'hyderabad' 'Unnao'
 'KOLKATA' 'Thane' 'Aurangabad' 'Belgaum' 'gurgoan' 'Dehradun' 'Rudrapur'
 'Jamshedpur' 'vizag' 'Nouda' 'Dharamshala' 'Banagalore' 'Hissar' 'Ranchi'
 'BANGALORE' 'Madurai' 'Gurga' 'Chandigarh' 'Australia' ' Chennai'
 'CHEYYAR' 'Mumbai ' 'sonepat' 'Ghaziabad' 'Pantnagar' 'Siliguri'
 'mumbai ' 'Jagdalpur' 'Chennai ' 'angul' 'Baroda' ' ariyalur' 'Jowai'
 'Kochi/Cochin, Chennai and Coimbatore' 'bhubaneswar' 'Neemrana' 'VIZAG'
 'Tirupathi' 'Lucknow ' 'Ahmedabad ' 'Bhubneshwar' 'Noida ' 'pune '
 'Calicut' 'Gandhinagar' 'LUCKNOW' 'Dubai' 'bengaluru' 'MUMBAI'
 'Ahmednagar' 'Nashik' 'New delhi' 'Bellary' 'Ludhiana' 'New Delhi '
 'Muzaffarnagar' 'BHOPAL' 'Gurgoan' 'Gagret' 'Indirapuram, Ghaziabad'
 'Gwalior' 'new delhi' 'TRIVANDRUM' 'Chennai & Mumbai' 'Rajasthan'
 'Sonipat' 'Bareli' 'Kanpur' 'Hospete' 'Miryalaguda' ' mumbai' 'Dharuhera'
 'lucknow' 'meerut' 'dehradun' 'Ganjam' 'Hubli' 'bangalore ' 'NAVI MUMBAI'
 'ncr' 'Agra' 'Trichy' 'kudankulam ,tarapur' 'Ongole' 'Sambalpur'
 'Pondicherry' 'Bundi' 'SADULPUR,RAJGARH,DISTT-CHURU,RAJASTHAN' 'AM'
 'Bikaner' 'Vadodara' 'BAngalore' 'india' 'Asansol' 'Tirunelvelli'
 'Ernakulam' 'DELHI' 'Bilaspur' 'Chandrapur' 'Nanded' 'Dharmapuri'
 'Vandavasi' 'Rohtak' 'trivandrum' 'Nagpur ' 'Udaipur' 'Patna' 'banglore'
 'indore' 'Salem' 'Nasikcity' 'Gandhinagar ' 'Technopark, Trivandrum'
 'Bharuch' 'Tornagallu' 'Raipur' 'Kolkata ' 'Jaspur' 'Burdwan'
 'Bhubaneswar ' 'Shimla' 'ahmedabad' 'Gajiabaad' 'Jammu' 'Shahdol'
 'Muvattupuzha' 'Al Jubail,Saudi Arabia' 'Kalmar, Sweden' 'Secunderabad'
 'A-64,sec-64,noida' 'Ratnagiri' 'Jhajjar' 'Gulbarga'
 'hyderabad(bhadurpally)' 'Nalagarh' 'Chandigarh ' 'Jaipur '
 'Jeddah Saudi Arabia' ' Delhi' 'PATNA' 'SHAHDOL' 'Chennai, Bangalore'
 'Bhopal ' 'Jamnagar' 'PUNE' 'Tirupati' 'Gonda' 'jamnagar' 'chennai '
 'orissa' 'kharagpur' 'Trivandrum ' 'Navi Mumbai , Hyderabad' 'Joshimath'
 'chandigarh' 'Bathinda' 'Johannesburg' 'kala amb ' 'Karnal' 'LONDON'
 'Kota' 'Panchkula' 'Baddi HP' 'Nagari' 'Mettur, Tamil Nadu ' 'Durgapur'
 'pondi' 'Surat' 'Kurnool' 'kolhapur' 'Madurai ' 'GREATER NOIDA' 'Bhilai'
 ' Pune' 'hderabad' 'KOTA' 'thane' 'Vizag' 'Bahadurgarh'
 'Rayagada, Odisha' 'kakinada' 'GURGAON' 'Varanasi' 'punr' 'Nellore'
 'patna' 'Meerut' 'hyderabad ' 'Sahibabad' 'Howrah' 'BHUBANESWAR'
 'Trichur' 'Ambala' 'Khopoli' 'keral' 'Roorkee' 'Greater NOIDA'
 'Navi mumbai' 'ghaziabad' 'Allahabad' 'Delhi/NCR' 'Panchkula ' 'Ranchi '
 'Jalandhar' 'manesar' 'vapi' 'PILANI' 'muzzafarpur' 'RAS AL KHAIMAH'
 'bihar' 'singaruli' 'KANPUR' 'Banglore ' 'pondy' 'Mohali' 'Phagwara'
 ' Mumbai' ' bangalore' 'GURAGAON' 'Baripada' 'MEERUT' 'Yamuna Nagar'
 'shahibabad' 'sampla' 'Guwahati' 'Rourkela' 'Banaglore' 'Vellore' 'Dausa'
 'latur (Maharashtra )' 'NEW DELHI' 'kanpur' 'Mainpuri' 'karnal' 'Dammam'
 'Haldia' 'sambalpur' 'RAE BARELI' 'ranchi' 'jAipur' 'BANGLORE' 'Patiala'
 'Gorakhpur' 'new dehli' 'BANGALORE ' 'Ambala City' 'Karad' 'Rajpura'
 'Pilani' 'haryana' 'Asifabadbanglore']
<ArrowStringArray>
['f', 'm']
Length: 2, dtype: str
<DatetimeArray>
['1990-02-19 00:00:00', '1989-10-04 00:00:00', '1992-08-03 00:00:00',
 '1989-12-05 00:00:00', '1991-02-27 00:00:00', '1992-07-02 00:00:00',
 '1993-02-01 00:00:00', '1992-05-27 00:00:00', '1991-09-17 00:00:00',
 '1993-06-13 00:00:00',
 ...
 '1992-12-15 00:00:00', '1988-09-05 00:00:00', '1987-12-27 00:00:00',
 '1991-03-30 00:00:00', '1993-01-24 00:00:00', '1989-12-07 00:00:00',
 '1986-08-05 00:00:00', '1986-02-28 00:00:00', '1990-06-22 00:00:00',
 '1987-04-15 00:00:00']
Length: 1872, dtype: datetime64[us]
[84.3  85.4  85.   85.6  78.   89.92 86.08 92.   90.   77.   88.6  81.
 83.6  60.8  81.2  69.54 85.8  65.   79.   91.2  75.67 92.5  70.   88.
 86.8  90.88 76.8  84.   64.   77.2  87.   73.   71.   91.5  52.33 66.6
 75.   91.4  59.   84.5  95.8  69.6  86.6  81.92 66.5  80.   85.2  89.25
 58.4  90.8  89.88 63.3  72.   83.   85.3  60.66 89.37 84.4  89.   86.
 70.6  93.44 76.   86.4  84.83 72.3  69.   73.33 86.16 56.   79.25 88.66
 80.8  81.16 83.5  55.6  84.6  62.   68.4  51.   79.6  63.4  86.53 76.18
 91.43 76.17 82.4  58.   90.04 60.4  74.23 59.8  82.3  84.2  60.   82.8
 82.6  74.   89.8  88.67 64.66 77.8  89.5  64.56 91.12 73.08 78.33 81.33
 89.7  87.4  92.66 76.87 91.3  77.9  76.2  77.78 65.6  65.8  67.75 91.6
 78.66 78.4  61.   90.4  58.6  82.2  82.   90.1  86.17 83.89 76.7  88.2
 80.6  91.   74.4  79.28 84.96 92.8  79.4  66.8  79.8  65.3  94.6  83.33
 80.83 67.23 86.2  55.   86.62 69.13 89.12 87.5  66.4  80.33 75.2  50.6
 81.1  60.14 78.83 75.8  77.66 64.48 67.   75.6  85.28 71.5  93.6  93.33
 78.8  82.16 77.65 56.5  79.83 57.   89.42 72.8  86.3  77.5  71.2  80.2
 73.6  68.   74.7  69.2  65.33 96.48 82.5  91.8  93.4  68.5  73.4  72.2
 71.8  66.33 71.67 70.2  90.27 67.67 53.4  76.16 65.71 79.5  87.2  80.4
 88.4  90.6  89.2  81.6  86.5  77.16 72.33 79.89 75.4  72.83 88.33 78.88
 95.2  89.33 75.3  69.8  52.   58.2  90.5  70.83 62.13 74.5  63.   73.37
 83.4  92.6  78.6  76.4  86.88 66.   70.67 65.1  68.14 92.2  93.5  82.83
 81.66 90.15 44.16 94.4  64.4  85.17 70.1  88.25 94.8  77.4  66.66 81.03
 44.   45.6  87.8  72.6  79.86 84.67 48.   53.3  71.66 68.8  78.15 83.43
 86.9  84.8  75.06 86.66 70.9  81.12 67.5  78.2  71.06 71.28 62.1  90.56
 87.6  71.3  88.8  86.09 67.72 76.6  68.6  63.43 70.4  67.6  73.8  55.5
 74.67 92.16 83.66 62.86 49.   87.11 77.53 88.5  61.9  79.2  83.8  79.33
 67.3  83.2  72.5  77.67 94.2  59.33 87.63 89.76 84.14 88.17 59.6  64.3
 75.04 82.9  73.5  73.67 77.7  87.69 83.16 71.32 61.6  61.8  85.06 91.71
 75.46 74.8  67.4  90.3  86.15 64.7  69.7  82.33 58.83 75.36 76.5  66.67
 67.2  80.88 88.88 71.4  65.2  96.   61.2  81.4  68.66 65.56 86.7  63.2
 62.2  68.2  77.85 83.3  56.78 83.04 71.1  76.53 74.83 59.3  73.2  86.33
 64.83 72.1  61.1  86.83 70.8  94.   80.3  64.6  84.1  84.93 92.83 89.6
 80.5  83.82 77.57 51.2  66.46 82.67 61.4  69.4  90.24 75.75 90.83 89.1
 87.33 83.1  88.34 91.67 87.3  48.8  75.38 55.52 71.05 77.63 92.47 93.
 68.33 79.16 85.33 80.42 78.25 95.52 87.86 89.4  94.7  97.12 93.94 59.57
 80.53 81.9  63.6  66.16 62.5  69.5  80.93 82.7  79.29 81.5  62.34 83.68
 70.66 60.1  77.38 68.83 94.43 85.53 88.09 74.2  85.73 72.4  67.7  79.78
 81.3  79.37 85.5  87.83 70.33 80.64 58.7  60.2  77.81 85.67 89.9  79.75
 75.73 87.68 60.5  81.38 75.52 48.5  88.3  82.1  85.18 81.8  90.46 70.5
 79.52 89.29 61.75 78.67 71.6  80.13 81.67 95.   81.14 72.16 87.04 88.64
 82.56 90.01 63.66 65.17 91.84 92.1  43.   65.23 92.48 82.88 73.07 58.56
 85.83 67.34 85.75 80.7  79.23 70.26 52.7  75.86 90.16 90.2  78.5  58.9
 80.32 67.16 73.06 92.93 85.76 87.52 88.36 81.73 60.7  87.7  79.85 68.9
 73.83 64.8  77.84 74.14 64.28 92.4  73.94 63.33 70.06 88.7  89.3  83.83
 91.33 80.07 72.17 63.5  69.17 67.42 84.16 76.64 78.13 61.69 81.7  82.46
 64.57 78.1  66.3  59.71 80.67 77.88 88.53 93.38 52.93 78.17 72.36 84.75
 86.67 77.6  74.3  62.4  65.16 59.2  69.85 79.68 65.4  94.72 71.86 81.25
 87.62 54.   85.92 74.33 82.28 75.1  69.73 92.12 70.3  76.33 80.1  76.67
 77.83 57.67 83.14 50.   91.21 81.83 78.16 80.14 93.3  61.63 73.73 80.46
 76.48 82.25 56.16 57.88 87.07 67.1  87.73 77.12 64.53 86.46 82.62 53.06
 74.62 76.66 45.33 69.69 53.   75.33 74.28 74.6  74.88 74.53 46.24 80.15
 86.13 85.72 51.36 78.53 53.8  86.1  84.43 76.36 77.86 88.83 88.18 79.14
 54.5  84.33 78.3  77.44 87.31 58.16 61.3  77.33 75.12 72.12 65.26 83.56
 50.5  82.27 67.36 87.16 75.83 78.44 91.9  68.3  92.64 58.17 83.46 88.04
 70.58 71.17 84.13 64.62 66.15 67.8  57.78 56.2  61.5  94.1  74.16 78.93
 70.56 85.16 82.26 71.13 65.66 71.71 86.37 88.57 59.05 79.66 89.39 95.54
 55.3  70.14 87.23 85.38 86.92 95.04 95.6  60.83 71.33 94.16 78.57 80.16
 70.25 82.13 88.76 51.6  70.76 57.5  68.67 74.18 68.25 71.04 64.43 82.24
 90.06 67.12 75.85 87.81 76.93 65.5  92.3  50.66 61.83 63.16 64.2  53.6
 83.69 80.04 78.86 70.61 62.8  67.06 65.85 94.24 63.8  75.77 94.5  71.83
 91.1  91.52 90.08 93.16 86.34 88.1  97.   62.93 76.96 85.46 78.08 66.7
 95.86 92.09 81.46 81.86 61.73 77.22 46.8  79.3  72.75 93.8  93.67 75.16
 72.45 85.62 86.85 93.28 58.33 64.33 75.62 54.8  58.5  91.68 69.3  62.6
 65.41 91.62 88.16 92.32 69.83 83.67 69.92 52.5  56.4  54.6  78.61 69.53
 75.71 71.84 70.16 69.66 95.4  84.62 91.53 85.66 61.57 80.63 69.33 62.3
 87.87 70.75 87.58 58.8  62.88 73.66 97.76 88.44 54.83 67.25 90.76 82.75
 75.66 91.04 90.58 91.86 73.1  73.3  69.1  51.83 62.26 65.67 68.65 51.42
 78.28 80.58 55.33 91.17 74.9  93.43 90.81 89.89 62.67 90.26 62.15 70.08
 87.88 72.67 93.2  60.46 71.07 46.   54.4  86.12 72.15 71.85 49.9  83.75
 71.73 90.33 86.14 66.2  88.75 67.33 57.14 67.76 82.66 77.92 79.38 67.17
 89.17 79.67 96.8  71.37 82.87 89.44 71.76 57.7  89.23 79.06 83.25 61.86
 89.56 82.14 70.27 59.7  93.07 79.9  64.5  66.85 69.16 52.09 78.72]
['board ofsecondary education,ap' 'cbse' 'state board' 'mp board bhopal'
 'icse' 'karnataka secondary school of examination' 'up'
 'karnataka state education examination board' 'ssc'
 'kerala state technical education' 0 'bseb'
 'state board of secondary education, andhra pradesh' 'matriculation'
 'gujarat state board' 'karnataka state board' 'wbbse'
 'maharashtra state board' 'icse board' 'up board'
 'board of secondary education(bse) orissa'
 'little jacky matric higher secondary school' 'uttar pradesh board'
 'bsc,orissa' 'mp board' 'upboard' 'matriculation board' 'j & k bord'
 'rbse' 'central board of secondary education' 'pseb' 'jkbose'
 'haryana board of school education,(hbse)' 'metric' 'ms board' 'kseeb'
 'stateboard' 'maticulation' 'karnataka secondory education board'
 'mumbai board' 'sslc' 'kseb' 'board secondary  education' 'matric board'
 'board of secondary education' 'west bengal board of secondary education'
 'jharkhand secondary examination board,ranchi' 'u p board' 'bseb,patna'
 'hsc' 'bse' 'sss pune' 'karnataka education board (keeb)' 'kerala'
 'state board of secondary education( ssc)' 'gsheb' 'up(allahabad)'
 'nagpur' 'don bosco maatriculation school'
 'karnataka state secondary education board' 'maharashtra'
 'karnataka secondary education board'
 'himachal pradesh board of school education'
 'certificate of middle years program of ib'
 'karnataka board of secondary education'
 'board of secondary education rajasthan' 'uttarakhand board' 'ua'
 'board of secendary education orissa'
 'karantaka secondary education and examination borad' 'hbsc'
 'kseeb(karnataka secondary education examination board)'
 'cbse[gulf zone]' 'hbse' 'state(karnataka board)'
 'jharkhand accademic council'
 'jharkhand secondary examination board (ranchi)'
 'karnataka secondary education examination board' 'delhi board'
 'mirza ahmed ali baig' 'jseb' 'bse, odisha' 'bihar board'
 'maharashtra state(latur board)' 'rajasthan board' 'mpboard' 'upbhsie'
 'secondary board of rajasthan' 'tamilnadu matriculation board'
 'jharkhand secondary board'
 'board of secondary education,andhara pradesh' 'up baord' 'state'
 'board of intermediate education'
 'state board of secondary education,andhra pradesh'
 'up board , allahabad' 'stjosephs girls higher sec school,dindigul'
 'maharashtra board' 'education board of kerala' 'board of ssc'
 'maharashtra state board pune' 'board of school education harayana'
 'secondary school cerfificate' 'maharashtra sate board' 'ksseb'
 'bihar examination board, patna' 'latur'
 'board of secondary education, rajasthan' 'state borad hp' 'cluny'
 'bsepatna' 'up borad' 'ssc board of andrapradesh' 'matric' 'bse,orissa'
 'ssc-andhra pradesh' 'mp' 'karnataka education board' 'mhsbse'
 'karnataka sslc board bangalore' 'karnataka' 'u p'
 'secondary school of education' 'state board of karnataka'
 'karnataka secondary board' 'andhra pradesh board ssc'
 'stjoseph of cluny matrhrsecschool,neyveli,cuddalore district'
 'hse,orissa' 'national public school' 'nagpur board'
 'jharkhand academic council' 'bsemp'
 'board of secondary education, andhra pradesh'
 'board of secondary education orissa'
 'board of secondary education,rajasthan(rbse)'
 'board of secondary education,ap'
 'board of secondary education,andhra pradesh'
 'jawahar navodaya vidyalaya' 'aisse'
 'karnataka board of higher education' 'bihar' 'kerala state board'
 'cicse' 'tn state board' 'kolhapur divisional board, maharashtra'
 'bharathi matriculation school' 'uttaranchal state board' 'wbbsce'
 'mp state board' 'seba(assam)' 'anglo indian' 'gseb' 'uttar pradesh'
 'ghseb' 'board of school education uttarakhand' 'msbshse,pune'

In [5]:
num_1=df.select_dtypes(include=['Int64','Float64'])
print(num_1)

          ID   Salary  10percentage  12graduation  12percentage  CollegeID  \
0     203097   420000         84.30          2007         95.80       1141
1     579905   500000         85.40          2007         85.00       5807
2     810601   325000         85.00          2010         68.20         64
3     267447  1100000         85.60          2007         83.60       6920
4     343523   200000         78.00          2008         76.80      11368
...      ...      ...           ...           ...           ...        ...
3993   47916   280000         52.09          2006         55.50       6268
3994  752781   100000         90.00          2009         93.00       4883
3995  355888   320000         81.86          2008         65.50       9786
3996  947111   200000         78.72          2010         69.88        979
3997  324966   400000         70.60          2008         68.00       6609

      CollegeTier  collegeGPA  CollegeCityID  CollegeCityTier  ...  \
0               2       78.00           1141                0  ...
1               2       70.06           5807                0  ...
2               2       70.00             64                0  ...
3               1       74.64           6920                1  ...
4               2       73.90          11368                0  ...
...           ...         ...            ...              ...  ...
3993            2       61.50           6268                0  ...
3994            2       77.30           4883                1  ...
3995            2       70.00           9786                0  ...
3996            2       70.42            979                1  ...
3997            2       68.00           6609                1  ...

      ComputerScience  MechanicalEngg  ElectricalEngg  TelecomEngg  CivilEngg  \
0                  -1              -1              -1           -1         -1
1                  -1              -1              -1           -1         -1
2                  -1              -1              -1           -1         -1
3                  -1              -1              -1           -1         -1
4                  -1              -1              -1           -1         -1
...               ...             ...             ...          ...        ...
3993               -1              -1              -1           -1         -1
3994               -1              -1              -1           -1         -1
3995               -1              -1              -1           -1         -1
3996              438              -1              -1           -1         -1
3997               -1              -1              -1           -1         -1

      conscientiousness  agreeableness  extraversion  nueroticism  \
0                0.9737         0.8128        0.5269      1.35490
1               -0.7335         0.3789        1.2396     -0.10760
2                0.2718         1.7109        0.1637     -0.86820
3                0.0464         0.3448       -0.3440     -0.40780
4               -0.8810        -0.2793       -1.0697      0.09163
...                 ...            ...           ...          ...
3993            -0.1082         0.3448        0.2366      0.64980
3994            -0.3027         0.8784        0.9322      0.77980
3995            -1.5765        -1.5273       -1.5051     -1.31840
3996            -0.1590         0.0459       -0.4511     -0.36120
3997            -1.1128        -0.2793       -0.6343      1.32553

      openess_to_experience
0                   -0.4455
1                    0.8637
2                    0.6721
3                   -0.9194
4                   -0.1295
...                     ...
3993                -0.9194
3994                -0.0943
3995                -0.7615
3996                -0.0943
3997                -0.6035

[3998 rows x 27 columns]

In [6]:
print(df.isna().sum())

Unnamed: 0               0
ID                       0
Salary                   0
DOJ                      0
DOL                      0
Designation              0
JobCity                  0
Gender                   0
DOB                      0
10percentage             0
10board                  0
12graduation             0
12percentage             0
12board                  0
CollegeID                0
CollegeTier              0
Degree                   0
Specialization           0
collegeGPA               0
CollegeCityID            0
CollegeCityTier          0
CollegeState             0
GraduationYear           0
English                  0
Logical                  0
Quant                    0
Domain                   0
ComputerProgramming      0
ElectronicsAndSemicon    0
ComputerScience          0
MechanicalEngg           0
ElectricalEngg           0
TelecomEngg              0
CivilEngg                0
conscientiousness        0
agreeableness            0
extraversion             0
nueroticism              0
openess_to_experience    0
dtype: int64

In [2]:
import pandas as pd
df=pd.read_excel("data.xlsx")
high_salary=df[df["Salary"]>50000]
print(high_salary)

     Unnamed: 0      ID   Salary        DOJ                  DOL  \
0         train  203097   420000 2012-06-01              present
1         train  579905   500000 2013-09-01              present
2         train  810601   325000 2014-06-01              present
3         train  267447  1100000 2011-07-01              present
4         train  343523   200000 2014-03-01  2015-03-01 00:00:00
...         ...     ...      ...        ...                  ...
3993      train   47916   280000 2011-10-01  2012-10-01 00:00:00
3994      train  752781   100000 2013-07-01  2013-07-01 00:00:00
3995      train  355888   320000 2013-07-01              present
3996      train  947111   200000 2014-07-01  2015-01-01 00:00:00
3997      train  324966   400000 2013-02-01              present

                      Designation           JobCity Gender        DOB  \
0         senior quality engineer         Bangalore      f 1990-02-19
1               assistant manager            Indore      m 1989-10-04
2                systems engineer           Chennai      f 1992-08-03
3        senior software engineer           Gurgaon      m 1989-12-05
4                             get           Manesar      m 1991-02-27
...                           ...               ...    ...        ...
3993            software engineer        New Delhi       m 1987-04-15
3994             technical writer         Hyderabad      f 1992-08-27
3995  associate software engineer         Bangalore      m 1991-07-03
3996           software developer  Asifabadbanglore      f 1992-03-20
3997      senior systems engineer           Chennai      f 1991-02-26

      10percentage  ... ComputerScience  MechanicalEngg  ElectricalEngg  \
0            84.30  ...              -1              -1              -1
1            85.40  ...              -1              -1              -1
2            85.00  ...              -1              -1              -1
3            85.60  ...              -1              -1              -1
4            78.00  ...              -1              -1              -1
...            ...  ...             ...             ...             ...
3993         52.09  ...              -1              -1              -1
3994         90.00  ...              -1              -1              -1
3995         81.86  ...              -1              -1              -1
3996         78.72  ...             438              -1              -1
3997         70.60  ...              -1              -1              -1

     TelecomEngg  CivilEngg  conscientiousness agreeableness extraversion  \
0             -1         -1             0.9737        0.8128       0.5269
1             -1         -1            -0.7335        0.3789       1.2396
2             -1         -1             0.2718        1.7109       0.1637
3             -1         -1             0.0464        0.3448      -0.3440
4             -1         -1            -0.8810       -0.2793      -1.0697
...          ...        ...                ...           ...          ...
3993          -1         -1            -0.1082        0.3448       0.2366
3994          -1         -1            -0.3027        0.8784       0.9322
3995          -1         -1            -1.5765       -1.5273      -1.5051
3996          -1         -1            -0.1590        0.0459      -0.4511
3997          -1         -1            -1.1128       -0.2793      -0.6343

      nueroticism  openess_to_experience
0         1.35490                -0.4455
1        -0.10760                 0.8637
2        -0.86820                 0.6721
3        -0.40780                -0.9194
4         0.09163                -0.1295
...           ...                    ...
3993      0.64980                -0.9194
3994      0.77980                -0.0943
3995     -1.31840                -0.7615
3996     -0.36120                -0.0943
3997      1.32553                -0.6035

[3984 rows x 39 columns]

In [7]:
female=df[df["Gender"]=="f"]
female.head()

,Unnamed: 0,ID,Salary,DOJ,DOL,Designation,JobCity,Gender,DOB,10percentage,...,ComputerScience,MechanicalEngg,ElectricalEngg,TelecomEngg,CivilEngg,conscientiousness,agreeableness,extraversion,nueroticism,openess_to_experience
0,train,203097,420000,2012-06-01,present,senior quality engineer,Bangalore,f,1990-02-19,84.30,...,-1,-1,-1,-1,-1,0.9737,0.8128,0.5269,1.3549,-0.4455
2,train,810601,325000,2014-06-01,present,systems engineer,Chennai,f,1992-08-03,85.00,...,-1,-1,-1,-1,-1,0.2718,1.7109,0.1637,-0.8682,0.6721
15,train,536517,350000,2013-08-01,present,network engineer,-1,f,1990-01-17,69.54,...,-1,-1,-1,-1,-1,1.7465,1.9048,0.6720,-0.2902,1.2528
19,train,466888,325000,2014-09-01,present,software engineer,Pune,f,1990-11-30,79.00,...,-1,-1,-1,-1,-1,0.8192,0.2668,-0.2714,-0.4078,-0.1295
20,train,140069,320000,2010-11-01,2012-09-01 00:00:00,software engineer,Bangalore,f,1988-07-25,91.20,...,-1,-1,-1,-1,-1,-0.1082,0.9688,0.5269,-0.2902,0.3444

In [6]:
male=df[df["Gender"]=="m"]
male.head()

,Unnamed: 0,ID,Salary,DOJ,DOL,Designation,JobCity,Gender,DOB,10percentage,...,ComputerScience,MechanicalEngg,ElectricalEngg,TelecomEngg,CivilEngg,conscientiousness,agreeableness,extraversion,nueroticism,openess_to_experience
1,train,579905,500000,2013-09-01,present,assistant manager,Indore,m,1989-10-04,85.40,...,-1,-1,-1,-1,-1,-0.7335,0.3789,1.2396,-0.10760,0.8637
3,train,267447,1100000,2011-07-01,present,senior software engineer,Gurgaon,m,1989-12-05,85.60,...,-1,-1,-1,-1,-1,0.0464,0.3448,-0.3440,-0.40780,-0.9194
4,train,343523,200000,2014-03-01,2015-03-01 00:00:00,get,Manesar,m,1991-02-27,78.00,...,-1,-1,-1,-1,-1,-0.8810,-0.2793,-1.0697,0.09163,-0.1295
5,train,1027655,300000,2014-06-01,present,system engineer,Hyderabad,m,1992-07-02,89.92,...,407,-1,-1,-1,-1,-0.3027,-0.6201,-2.2954,-0.74150,-0.8608
6,train,947847,300000,2014-08-01,2015-05-01 00:00:00,java software engineer,Banglore,m,1993-02-01,86.08,...,346,-1,-1,-1,-1,1.7081,-0.1054,-1.0379,-2.00920,-1.0872

In [8]:
bang_people=df[df["JobCity"]=="Banglore"]
bang_people.head()

,Unnamed: 0,ID,Salary,DOJ,DOL,Designation,JobCity,Gender,DOB,10percentage,...,ComputerScience,MechanicalEngg,ElectricalEngg,TelecomEngg,CivilEngg,conscientiousness,agreeableness,extraversion,nueroticism,openess_to_experience
6,train,947847,300000,2014-08-01,2015-05-01 00:00:00,java software engineer,Banglore,m,1993-02-01,86.08,...,346,-1,-1,-1,-1,1.7081,-0.1054,-1.0379,-2.0092,-1.0872
648,train,1119098,180000,2015-01-01,present,technical support engineer,Banglore,f,1993-05-28,74.00,...,315,-1,-1,-1,-1,1.2772,1.3779,1.0859,1.0333,1.0554
1722,train,243949,600000,2012-02-01,present,sr. database engineer,Banglore,m,1990-04-15,74.00,...,-1,-1,-1,260,-1,0.5100,-0.7473,0.6720,-0.7603,0.0284
2296,train,504027,325000,2014-02-01,present,application developer,Banglore,f,1990-08-24,85.40,...,-1,-1,-1,-1,-1,0.1623,1.5928,0.5269,-1.5828,0.3444
2338,train,942616,160000,2010-07-01,2011-11-01 00:00:00,assistant manager,Banglore,m,1987-09-05,87.80,...,-1,-1,-1,-1,-1,0.4034,0.4934,-0.6339,-1.3255,0.7631

In [9]:
salary_range=df[df["Salary"]>=30000 & (df["Salary"]<=50000)]
print(salary_range.head())

  Unnamed: 0      ID   Salary        DOJ                  DOL  \
0      train  203097   420000 2012-06-01              present
1      train  579905   500000 2013-09-01              present
2      train  810601   325000 2014-06-01              present
3      train  267447  1100000 2011-07-01              present
4      train  343523   200000 2014-03-01  2015-03-01 00:00:00

                Designation    JobCity Gender        DOB  10percentage  ...  \
0   senior quality engineer  Bangalore      f 1990-02-19          84.3  ...
1         assistant manager     Indore      m 1989-10-04          85.4  ...
2          systems engineer    Chennai      f 1992-08-03          85.0  ...
3  senior software engineer    Gurgaon      m 1989-12-05          85.6  ...
4                       get    Manesar      m 1991-02-27          78.0  ...

  ComputerScience  MechanicalEngg  ElectricalEngg TelecomEngg  CivilEngg  \
0              -1              -1              -1          -1         -1
1              -1              -1              -1          -1         -1
2              -1              -1              -1          -1         -1
3              -1              -1              -1          -1         -1
4              -1              -1              -1          -1         -1

   conscientiousness agreeableness extraversion  nueroticism  \
0             0.9737        0.8128       0.5269      1.35490
1            -0.7335        0.3789       1.2396     -0.10760
2             0.2718        1.7109       0.1637     -0.86820
3             0.0464        0.3448      -0.3440     -0.40780
4            -0.8810       -0.2793      -1.0697      0.09163

   openess_to_experience
0                -0.4455
1                 0.8637
2                 0.6721
3                -0.9194
4                -0.1295

[5 rows x 39 columns]

In [11]:
cities=df[(df["JobCity"]=="Chennai")|(df["JobCity"]=="Hyderabad")]
print(cities.head())

   Unnamed: 0       ID  Salary        DOJ                  DOL  \
2       train   810601  325000 2014-06-01              present
5       train  1027655  300000 2014-06-01              present
22      train   995191  190000 2013-10-01  2015-04-01 00:00:00
24      train   963123  335000 2014-06-01  2015-06-01 00:00:00
30      train   192703  530000 2011-12-01              present

           Designation    JobCity Gender        DOB  10percentage  ...  \
2     systems engineer    Chennai      f 1992-08-03         85.00  ...
5      system engineer  Hyderabad      m 1992-07-02         89.92  ...
22           developer  Hyderabad      m 1992-01-23         92.50  ...
24  programmer analyst  Hyderabad      m 1993-06-28         88.00  ...
30    systems engineer  Hyderabad      m 1989-10-04         84.00  ...

   ComputerScience  MechanicalEngg  ElectricalEngg TelecomEngg  CivilEngg  \
2               -1              -1              -1          -1         -1
5              407              -1              -1          -1         -1
22              -1              -1              -1          -1         -1
24             346              -1              -1          -1         -1
30              -1              -1              -1          -1         -1

    conscientiousness agreeableness extraversion  nueroticism  \
2              0.2718        1.7109       0.1637      -0.8682
5             -0.3027       -0.6201      -2.2954      -0.7415
22            -0.4463       -0.6201      -0.6048       0.7798
24             0.4155        0.8027       0.1357      -0.9950
30            -0.4173        0.6568      -0.0537      -1.2303

    openess_to_experience
2                  0.6721
5                 -0.8608
22                -2.7769
24                -0.6692
30                -0.9194

[5 rows x 39 columns]

In [ ]:
multi_cities=['Banglore','Hyderbad','Chennai']
df[df['JobCity'].isin(multi_cities)]

,Unnamed: 0,ID,Salary,DOJ,DOL,Designation,JobCity,Gender,DOB,10percentage,...,ComputerScience,MechanicalEngg,ElectricalEngg,TelecomEngg,CivilEngg,conscientiousness,agreeableness,extraversion,nueroticism,openess_to_experience
2,train,810601,325000,2014-06-01,present,systems engineer,Chennai,f,1992-08-03,85.00,...,-1,-1,-1,-1,-1,0.2718,1.7109,0.1637,-0.86820,0.6721
6,train,947847,300000,2014-08-01,2015-05-01 00:00:00,java software engineer,Banglore,m,1993-02-01,86.08,...,346,-1,-1,-1,-1,1.7081,-0.1054,-1.0379,-2.00920,-1.0872
45,train,1230582,110000,2014-09-01,2015-01-01 00:00:00,production engineer,Chennai,m,1992-10-12,95.80,...,-1,253,-1,-1,-1,-0.5899,-1.1196,0.4711,-0.74150,-1.4356
60,train,652717,305000,2013-11-01,present,software engineer,Chennai,f,1991-12-27,83.00,...,-1,-1,-1,-1,-1,-0.1590,-0.1206,0.1637,1.54040,-0.0943
61,train,940402,300000,2014-10-01,2015-04-01 00:00:00,java developer,Chennai,m,1993-06-30,85.30,...,346,-1,-1,-1,-1,1.8517,1.5444,0.3174,0.39950,0.6721
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3889,train,1062520,325000,2014-10-01,present,assistant store manager,Chennai,m,1993-08-28,93.40,...,-1,-1,-1,-1,-1,0.1282,0.3789,-1.5270,-0.86820,-0.6692
3933,train,116358,490000,2011-02-01,present,system engineer,Chennai,m,1989-01-21,87.00,...,-1,-1,-1,-1,-1,0.6646,0.1888,0.2366,0.06230,0.1864
3940,train,1100767,300000,2014-08-01,present,software engineer,Chennai,f,1993-08-01,81.00,...,346,-1,-1,-1,-1,1.1336,0.3789,-0.4511,0.01920,0.6721
3953,train,331779,160000,2013-05-01,present,software test engineer,Chennai,m,1990-01-26,79.20,...,-1,-1,-1,-1,-1,-1.0355,-2.0733,-1.2511,0.17983,-1.5513
3997,train,324966,400000,2013-02-01,present,senior systems engineer,Chennai,f,1991-02-26,70.60,...,-1,-1,-1,-1,-1,-1.1128,-0.2793,-0.6343,1.32553,-0.6035

In [15]:
df.sort_values(by=['Gender','Salary'],
ascending=[True,False]
)
df.sort_values(by='Salary')

,Unnamed: 0,ID,Salary,DOJ,DOL,Designation,JobCity,Gender,DOB,10percentage,...,ComputerScience,MechanicalEngg,ElectricalEngg,TelecomEngg,CivilEngg,conscientiousness,agreeableness,extraversion,nueroticism,openess_to_experience
3473,train,1272092,35000,2014-05-01,2015-05-01 00:00:00,.net developer,hyderabad,m,1993-01-08,85.30,...,376,-1,-1,-1,-1,-3.7496,-5.6151,-3.8324,-0.48790,-7.3757
2627,train,242100,35000,2012-03-01,present,systems engineer,Noida,m,1989-11-24,88.00,...,-1,-1,-1,-1,-1,0.2009,0.0328,-0.9245,0.29730,-0.1295
194,train,211840,35000,2012-01-01,present,systems engineer,Gurgaon,f,1989-08-16,86.00,...,-1,-1,-1,-1,-1,-2.5811,0.0328,0.3817,0.41480,-1.0774
3231,train,578157,40000,2013-10-01,2014-07-01 00:00:00,application developer,Bangalore,m,1991-04-01,64.00,...,-1,-1,-1,-1,-1,1.8517,0.2124,2.1617,-2.00920,-0.2859
1837,train,619423,40000,2013-11-01,2014-11-01 00:00:00,product design engineer,-1,m,1992-06-03,79.20,...,-1,-1,433,-1,-1,-1.0208,-0.7866,-1.0659,-0.36120,-2.5853
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
500,train,260866,2600000,2011-07-01,2013-04-01 00:00:00,application developer,-1,m,1989-05-27,86.60,...,-1,-1,-1,-1,-1,0.3555,0.9688,0.0914,-0.87780,-0.7615
1759,train,1283923,3000000,2014-09-01,2015-03-01 00:00:00,programmer,-1,m,1992-08-01,89.00,...,-1,-1,-1,-1,-1,-0.0154,0.7119,0.4711,-0.61470,0.2889
779,train,325412,3500000,2013-01-01,2014-10-01 00:00:00,assistant system engineer,Pune,f,1990-08-07,76.80,...,-1,-1,-1,-1,-1,0.1623,0.3448,-0.3440,-0.17277,0.6603
1237,train,48107,4000000,2010-07-01,2015-03-01 00:00:00,senior software engineer,New Delhi,m,1987-09-09,90.83,...,-1,-1,-1,-1,-1,-0.7264,0.0328,-1.6502,-0.87780,-0.1295
2182,train,41147,4000000,2010-01-01,2011-12-01 00:00:00,automation engineer,gurgaon,m,1987-09-13,53.00,...,-1,-1,-1,-1,-1,-3.3539,-0.4353,-1.0697,-0.05520,-2.6572

In [16]:
df.groupby('Gender')['Salary'].agg(['min','max','count','mean'])

          min      max  count           mean
Gender
f       35000  3500000    957  294937.304075
m       35000  4000000   3041  311716.211772

In [17]:
df.groupby(['Gender','Designation'])['Salary'].agg(['min','max','count','mean'])

                                                 min     max  count  \
Gender Designation
f      .net developer                         100000  440000      8
       .net web developer                     305000  305000      1
       account executive                       85000  300000      2
       administrative support                 200000  200000      1
       aircraft technician                    100000  100000      1
...                                              ...     ...    ...
m      web application developer              120000  340000      5
       web designer                           160000  280000      4
       web designer and joomla administrator   60000   60000      1
       web developer                           60000  330000     37
       website developer/tester               200000  200000      1

                                                       mean
Gender Designation
f      .net developer                         252500.000000
       .net web developer                     305000.000000
       account executive                      192500.000000
       administrative support                 200000.000000
       aircraft technician                    100000.000000
...                                                     ...
m      web application developer              187000.000000
       web designer                           207500.000000
       web designer and joomla administrator   60000.000000
       web developer                          178108.108108
       website developer/tester               200000.000000

[581 rows x 4 columns]

In [18]:
df.groupby('JobCity')['Salary'].agg(['min','max','count','mean'])

                 min      max  count           mean
JobCity
-1             40000  3000000    461  303318.872017
 Chennai      335000   335000      1  335000.000000
 Delhi        360000   360000      1  360000.000000
 Mumbai       110000   180000      2  145000.000000
 Pune         180000   180000      1  180000.000000
...              ...      ...    ...            ...
trivandrum    240000   325000      2  282500.000000
udaipur       100000   120000      2  110000.000000
vapi          180000   180000      1  180000.000000
vizag         260000   260000      1  260000.000000
vsakhapttnam  180000   180000      1  180000.000000

[339 rows x 4 columns]

In [ ]:
import pandas as pd
df=pd.read_excel("data.xlsx")
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
3993    False
3994    False
3995    False
3996    False
3997    False
Length: 3998, dtype: bool